import Head from "next/head"
import ProductsTable from "./Components/ProductsTable"

export default function Home() {
  return (
    <>
      <Head>
        <title>Products App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main_page">
        {/* Products component to render the datagrid */}
        <ProductsTable />
      </main>
    </>
  )
}
